name: Soyaine

frame_padding: 10px

column: 3
column_gap: 30px
row_gap: 30px

small_screen:
  column: 2
  column_gap: 10px
  row_gap: 10px

process:
  album:
    sort_by_time: True # False: sort by filename
    order_by: modify # access, create
    reverse: True
  photo:
    sort_by_time: False
    order_by: modify
    reverse: False
    min_width: 600
    watermark:
      thumbnail: False
      original: True
      fontsize: 40
      fontfamily: Eczar-Medium.ttf
      rotate: 0

instagram: 

sass:
  sass_dir: _sass
  style: compressed
